# Generated by Django 5.1.6 on 2025-04-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoadeptrai', '0004_remove_order_complete_alter_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMessage',
            new_name='Message',
        ),
    ]
