# Generated by Django 5.1.6 on 2025-04-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoadeptrai', '0005_rename_chatmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('customer', 'seller')},
        ),
    ]
